# ~/.config/tmux/colors.conf

set -g @thm_rosewater "#f5e0dc"
set -g @thm_flamingo "#f2cdcd"
set -g @thm_pink "#f5c2e7"
set -g @thm_mauve "#cba6f7"
set -g @thm_red "#f38ba8"
set -g @thm_maroon "#eba0ac"
set -g @thm_peach "#fab387"
set -g @thm_yellow "#f9e2af"
set -g @thm_green "#a6e3a1"
set -g @thm_teal "#94e2d5"
set -g @thm_sky "#89dceb"
set -g @thm_sapphire "#74c7ec"
set -g @thm_blue "#89b4fa"
set -g @thm_lavender "#b4befe"
set -g @thm_text "#cdd6f4"
set -g @thm_subtext1 "#bac2de"
set -g @thm_subtext0 "#a6adc8"
set -g @thm_overlay2 "#9399b2"
set -g @thm_overlay1 "#7f849c"
set -g @thm_overlay0 "#6c7086"
set -g @thm_surface2 "#585b70"
set -g @thm_surface1 "#45475a"
set -g @thm_surface0 "#313244"
set -g @thm_base "#1e1e2e"
set -g @thm_mantle "#181825"
set -g @thm_crust "#11111b"
